// <auto-generated />
using System;
using Application.DTO.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.DTO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220116113141_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application.Model.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HouseAddressString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkAddressString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Application.Model.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Permitted")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryName = "Cambodia",
                            Permitted = false
                        },
                        new
                        {
                            ID = 2,
                            CountryName = "Qatar",
                            Permitted = true
                        },
                        new
                        {
                            ID = 3,
                            CountryName = "South Korea",
                            Permitted = true
                        },
                        new
                        {
                            ID = 4,
                            CountryName = "North Korea",
                            Permitted = true
                        },
                        new
                        {
                            ID = 5,
                            CountryName = "Kazakhstan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 6,
                            CountryName = "Kyrgyzstan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 7,
                            CountryName = "Kuwait",
                            Permitted = true
                        },
                        new
                        {
                            ID = 8,
                            CountryName = "Georgia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 9,
                            CountryName = "Jordan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 10,
                            CountryName = "China",
                            Permitted = true
                        },
                        new
                        {
                            ID = 11,
                            CountryName = "Saudi Arabia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 12,
                            CountryName = "Syria",
                            Permitted = true
                        },
                        new
                        {
                            ID = 13,
                            CountryName = "Cyprus",
                            Permitted = true
                        },
                        new
                        {
                            ID = 14,
                            CountryName = "Japan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 15,
                            CountryName = "Timor-Leste",
                            Permitted = true
                        },
                        new
                        {
                            ID = 16,
                            CountryName = "Turkey",
                            Permitted = true
                        },
                        new
                        {
                            ID = 17,
                            CountryName = "Turkmenistan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 18,
                            CountryName = "Tajikistan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 19,
                            CountryName = "Thailand",
                            Permitted = true
                        },
                        new
                        {
                            ID = 20,
                            CountryName = "Nepal",
                            Permitted = true
                        },
                        new
                        {
                            ID = 21,
                            CountryName = "Brunei Darussalam",
                            Permitted = true
                        },
                        new
                        {
                            ID = 22,
                            CountryName = "Bangladesh",
                            Permitted = true
                        },
                        new
                        {
                            ID = 23,
                            CountryName = "Bahrain",
                            Permitted = true
                        },
                        new
                        {
                            ID = 24,
                            CountryName = "Pakistan",
                            Permitted = false
                        },
                        new
                        {
                            ID = 25,
                            CountryName = "Palestine",
                            Permitted = true
                        },
                        new
                        {
                            ID = 26,
                            CountryName = "Myanmar",
                            Permitted = false
                        },
                        new
                        {
                            ID = 27,
                            CountryName = "Philippines",
                            Permitted = true
                        },
                        new
                        {
                            ID = 28,
                            CountryName = "Bhutan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 29,
                            CountryName = "Mongolia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 30,
                            CountryName = "Maldives",
                            Permitted = true
                        },
                        new
                        {
                            ID = 31,
                            CountryName = "Malaysia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 32,
                            CountryName = "Yemen",
                            Permitted = true
                        },
                        new
                        {
                            ID = 33,
                            CountryName = "Laos",
                            Permitted = true
                        },
                        new
                        {
                            ID = 34,
                            CountryName = "Lebanon",
                            Permitted = true
                        },
                        new
                        {
                            ID = 35,
                            CountryName = "Vietnam",
                            Permitted = true
                        },
                        new
                        {
                            ID = 36,
                            CountryName = "Sri Lanka",
                            Permitted = true
                        },
                        new
                        {
                            ID = 37,
                            CountryName = "United Arab Emirates",
                            Permitted = true
                        },
                        new
                        {
                            ID = 38,
                            CountryName = "Singapore",
                            Permitted = true
                        },
                        new
                        {
                            ID = 39,
                            CountryName = "Afghanistan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 40,
                            CountryName = "Azerbaijan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 41,
                            CountryName = "Armenia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 42,
                            CountryName = "India",
                            Permitted = true
                        },
                        new
                        {
                            ID = 43,
                            CountryName = "Indonesia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 44,
                            CountryName = "Iraq",
                            Permitted = true
                        },
                        new
                        {
                            ID = 45,
                            CountryName = "Israel",
                            Permitted = true
                        },
                        new
                        {
                            ID = 46,
                            CountryName = "Iran",
                            Permitted = true
                        },
                        new
                        {
                            ID = 47,
                            CountryName = "Uzbekistan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 48,
                            CountryName = "Oman",
                            Permitted = true
                        },
                        new
                        {
                            ID = 49,
                            CountryName = "Kiribati",
                            Permitted = true
                        },
                        new
                        {
                            ID = 50,
                            CountryName = "Samoa",
                            Permitted = true
                        },
                        new
                        {
                            ID = 51,
                            CountryName = "Tonga",
                            Permitted = true
                        },
                        new
                        {
                            ID = 52,
                            CountryName = "Tuvalu",
                            Permitted = true
                        },
                        new
                        {
                            ID = 53,
                            CountryName = "Nauru",
                            Permitted = true
                        },
                        new
                        {
                            ID = 54,
                            CountryName = "New Zealand",
                            Permitted = true
                        },
                        new
                        {
                            ID = 55,
                            CountryName = "Papua New Guinea",
                            Permitted = true
                        },
                        new
                        {
                            ID = 56,
                            CountryName = "Palau",
                            Permitted = true
                        },
                        new
                        {
                            ID = 57,
                            CountryName = "Fiji",
                            Permitted = true
                        },
                        new
                        {
                            ID = 58,
                            CountryName = "Micronesia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 59,
                            CountryName = "Vanuatu",
                            Permitted = true
                        },
                        new
                        {
                            ID = 60,
                            CountryName = "Solomon Islands",
                            Permitted = true
                        },
                        new
                        {
                            ID = 61,
                            CountryName = "Marshall Islands",
                            Permitted = true
                        },
                        new
                        {
                            ID = 62,
                            CountryName = "Australia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 63,
                            CountryName = "Greece",
                            Permitted = true
                        },
                        new
                        {
                            ID = 64,
                            CountryName = "Kosovo",
                            Permitted = true
                        },
                        new
                        {
                            ID = 65,
                            CountryName = "Croatia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 66,
                            CountryName = "San Marino",
                            Permitted = true
                        },
                        new
                        {
                            ID = 67,
                            CountryName = "Serbia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 68,
                            CountryName = "Denmark",
                            Permitted = true
                        },
                        new
                        {
                            ID = 69,
                            CountryName = "Vatican City State",
                            Permitted = true
                        },
                        new
                        {
                            ID = 70,
                            CountryName = "Norway",
                            Permitted = true
                        },
                        new
                        {
                            ID = 71,
                            CountryName = "Netherlands",
                            Permitted = true
                        },
                        new
                        {
                            ID = 72,
                            CountryName = "Bosnia and Herzegovina",
                            Permitted = true
                        },
                        new
                        {
                            ID = 73,
                            CountryName = "Bulgaria",
                            Permitted = true
                        },
                        new
                        {
                            ID = 74,
                            CountryName = "Belgium",
                            Permitted = true
                        },
                        new
                        {
                            ID = 75,
                            CountryName = "Belarus",
                            Permitted = true
                        },
                        new
                        {
                            ID = 76,
                            CountryName = "Portugal",
                            Permitted = true
                        },
                        new
                        {
                            ID = 77,
                            CountryName = "Poland",
                            Permitted = true
                        },
                        new
                        {
                            ID = 78,
                            CountryName = "France",
                            Permitted = true
                        },
                        new
                        {
                            ID = 79,
                            CountryName = "Finland",
                            Permitted = true
                        },
                        new
                        {
                            ID = 80,
                            CountryName = "Montenegro",
                            Permitted = true
                        },
                        new
                        {
                            ID = 81,
                            CountryName = "Moldova",
                            Permitted = true
                        },
                        new
                        {
                            ID = 82,
                            CountryName = "Malta",
                            Permitted = true
                        },
                        new
                        {
                            ID = 83,
                            CountryName = "Monaco",
                            Permitted = true
                        },
                        new
                        {
                            ID = 84,
                            CountryName = "Ukraine",
                            Permitted = true
                        },
                        new
                        {
                            ID = 85,
                            CountryName = "Germany",
                            Permitted = true
                        },
                        new
                        {
                            ID = 86,
                            CountryName = "Russia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 87,
                            CountryName = "Romania",
                            Permitted = true
                        },
                        new
                        {
                            ID = 88,
                            CountryName = "Luxembourg",
                            Permitted = true
                        },
                        new
                        {
                            ID = 89,
                            CountryName = "Latvia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 90,
                            CountryName = "Liechtenstein",
                            Permitted = true
                        },
                        new
                        {
                            ID = 91,
                            CountryName = "Lithuania",
                            Permitted = true
                        },
                        new
                        {
                            ID = 92,
                            CountryName = "Spain",
                            Permitted = true
                        },
                        new
                        {
                            ID = 93,
                            CountryName = "Slovakia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 94,
                            CountryName = "Slovenia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 95,
                            CountryName = "Switzerland",
                            Permitted = true
                        },
                        new
                        {
                            ID = 96,
                            CountryName = "Sweden",
                            Permitted = true
                        },
                        new
                        {
                            ID = 97,
                            CountryName = "United Kingdom",
                            Permitted = true
                        },
                        new
                        {
                            ID = 98,
                            CountryName = "Czech Republic",
                            Permitted = true
                        },
                        new
                        {
                            ID = 99,
                            CountryName = "Republic of Macedonia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 100,
                            CountryName = "Austria",
                            Permitted = true
                        },
                        new
                        {
                            ID = 101,
                            CountryName = "Andorra",
                            Permitted = true
                        },
                        new
                        {
                            ID = 102,
                            CountryName = "Italy",
                            Permitted = true
                        },
                        new
                        {
                            ID = 103,
                            CountryName = "Estonia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 104,
                            CountryName = "Albania",
                            Permitted = true
                        },
                        new
                        {
                            ID = 105,
                            CountryName = "Iceland",
                            Permitted = true
                        },
                        new
                        {
                            ID = 106,
                            CountryName = "Ireland",
                            Permitted = true
                        },
                        new
                        {
                            ID = 107,
                            CountryName = "Hungary",
                            Permitted = true
                        },
                        new
                        {
                            ID = 108,
                            CountryName = "Ghana",
                            Permitted = true
                        },
                        new
                        {
                            ID = 109,
                            CountryName = "Gabon",
                            Permitted = true
                        },
                        new
                        {
                            ID = 110,
                            CountryName = "Cabo Verde",
                            Permitted = true
                        },
                        new
                        {
                            ID = 111,
                            CountryName = "Guinea",
                            Permitted = true
                        },
                        new
                        {
                            ID = 112,
                            CountryName = "Guinea-Bissau",
                            Permitted = true
                        },
                        new
                        {
                            ID = 113,
                            CountryName = "The Gambia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 114,
                            CountryName = "Côte d’Ivoire",
                            Permitted = true
                        },
                        new
                        {
                            ID = 115,
                            CountryName = "Comoros",
                            Permitted = true
                        },
                        new
                        {
                            ID = 116,
                            CountryName = "Kenya",
                            Permitted = true
                        },
                        new
                        {
                            ID = 117,
                            CountryName = "Cameroon",
                            Permitted = true
                        },
                        new
                        {
                            ID = 118,
                            CountryName = "Djibouti",
                            Permitted = true
                        },
                        new
                        {
                            ID = 119,
                            CountryName = "Chad",
                            Permitted = true
                        },
                        new
                        {
                            ID = 120,
                            CountryName = "Zimbabwe",
                            Permitted = true
                        },
                        new
                        {
                            ID = 121,
                            CountryName = "Sudan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 122,
                            CountryName = "Seychelles",
                            Permitted = true
                        },
                        new
                        {
                            ID = 123,
                            CountryName = "Senegal",
                            Permitted = true
                        },
                        new
                        {
                            ID = 124,
                            CountryName = "São Tomé and Príncipe",
                            Permitted = true
                        },
                        new
                        {
                            ID = 125,
                            CountryName = "South Sudan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 126,
                            CountryName = "Sierra Leone",
                            Permitted = true
                        },
                        new
                        {
                            ID = 127,
                            CountryName = "Zambia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 128,
                            CountryName = "Somalia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 129,
                            CountryName = "Tunisia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 130,
                            CountryName = "Togo",
                            Permitted = true
                        },
                        new
                        {
                            ID = 131,
                            CountryName = "Tanzania",
                            Permitted = true
                        },
                        new
                        {
                            ID = 132,
                            CountryName = "Namibia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 133,
                            CountryName = "Nigeria",
                            Permitted = true
                        },
                        new
                        {
                            ID = 134,
                            CountryName = "Niger",
                            Permitted = true
                        },
                        new
                        {
                            ID = 135,
                            CountryName = "Botswana",
                            Permitted = true
                        },
                        new
                        {
                            ID = 136,
                            CountryName = "Burundi",
                            Permitted = true
                        },
                        new
                        {
                            ID = 137,
                            CountryName = "Burkina Faso",
                            Permitted = true
                        },
                        new
                        {
                            ID = 138,
                            CountryName = "Benin",
                            Permitted = true
                        },
                        new
                        {
                            ID = 139,
                            CountryName = "Mauritius",
                            Permitted = true
                        },
                        new
                        {
                            ID = 140,
                            CountryName = "Mauritania",
                            Permitted = true
                        },
                        new
                        {
                            ID = 141,
                            CountryName = "Madagascar",
                            Permitted = true
                        },
                        new
                        {
                            ID = 142,
                            CountryName = "Malawi",
                            Permitted = true
                        },
                        new
                        {
                            ID = 143,
                            CountryName = "Mali",
                            Permitted = true
                        },
                        new
                        {
                            ID = 144,
                            CountryName = "Mozambique",
                            Permitted = true
                        },
                        new
                        {
                            ID = 145,
                            CountryName = "Morocco",
                            Permitted = true
                        },
                        new
                        {
                            ID = 146,
                            CountryName = "Uganda",
                            Permitted = true
                        },
                        new
                        {
                            ID = 147,
                            CountryName = "Rwanda",
                            Permitted = true
                        },
                        new
                        {
                            ID = 148,
                            CountryName = "Libya",
                            Permitted = true
                        },
                        new
                        {
                            ID = 149,
                            CountryName = "Lesotho",
                            Permitted = true
                        },
                        new
                        {
                            ID = 150,
                            CountryName = "Liberia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 151,
                            CountryName = "Swaziland",
                            Permitted = true
                        },
                        new
                        {
                            ID = 152,
                            CountryName = "Republic of the Congo",
                            Permitted = true
                        },
                        new
                        {
                            ID = 153,
                            CountryName = "Democratic Republic of the Congo",
                            Permitted = true
                        },
                        new
                        {
                            ID = 154,
                            CountryName = "Central African Republic",
                            Permitted = true
                        },
                        new
                        {
                            ID = 155,
                            CountryName = "Equatorial Guinea",
                            Permitted = true
                        },
                        new
                        {
                            ID = 156,
                            CountryName = "Egypt",
                            Permitted = true
                        },
                        new
                        {
                            ID = 157,
                            CountryName = "Ethiopia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 158,
                            CountryName = "Eritrea",
                            Permitted = true
                        },
                        new
                        {
                            ID = 159,
                            CountryName = "Angola",
                            Permitted = true
                        },
                        new
                        {
                            ID = 160,
                            CountryName = "South Africa",
                            Permitted = true
                        },
                        new
                        {
                            ID = 161,
                            CountryName = "Algeria",
                            Permitted = true
                        },
                        new
                        {
                            ID = 162,
                            CountryName = "Guatemala",
                            Permitted = true
                        },
                        new
                        {
                            ID = 163,
                            CountryName = "Grenada",
                            Permitted = true
                        },
                        new
                        {
                            ID = 164,
                            CountryName = "Costa Rica",
                            Permitted = true
                        },
                        new
                        {
                            ID = 165,
                            CountryName = "Cuba",
                            Permitted = true
                        },
                        new
                        {
                            ID = 166,
                            CountryName = "Canada",
                            Permitted = true
                        },
                        new
                        {
                            ID = 167,
                            CountryName = "Jamaica",
                            Permitted = true
                        },
                        new
                        {
                            ID = 168,
                            CountryName = "Saint Kitts and Nevis",
                            Permitted = true
                        },
                        new
                        {
                            ID = 169,
                            CountryName = "Saint Lucia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 170,
                            CountryName = "Saint Vincent and the Grenadines",
                            Permitted = true
                        },
                        new
                        {
                            ID = 171,
                            CountryName = "Dominica",
                            Permitted = true
                        },
                        new
                        {
                            ID = 172,
                            CountryName = "Nicaragua",
                            Permitted = true
                        },
                        new
                        {
                            ID = 173,
                            CountryName = "Barbados",
                            Permitted = true
                        },
                        new
                        {
                            ID = 174,
                            CountryName = "Bahamas",
                            Permitted = true
                        },
                        new
                        {
                            ID = 175,
                            CountryName = "Belize",
                            Permitted = true
                        },
                        new
                        {
                            ID = 176,
                            CountryName = "Panama",
                            Permitted = true
                        },
                        new
                        {
                            ID = 177,
                            CountryName = "Mexico",
                            Permitted = true
                        },
                        new
                        {
                            ID = 178,
                            CountryName = "United States of America",
                            Permitted = true
                        },
                        new
                        {
                            ID = 179,
                            CountryName = "Dominican Republic",
                            Permitted = true
                        },
                        new
                        {
                            ID = 180,
                            CountryName = "El Salvador",
                            Permitted = true
                        },
                        new
                        {
                            ID = 181,
                            CountryName = "Antigua and Barbuda",
                            Permitted = true
                        },
                        new
                        {
                            ID = 182,
                            CountryName = "Honduras",
                            Permitted = true
                        },
                        new
                        {
                            ID = 183,
                            CountryName = "Haiti",
                            Permitted = true
                        },
                        new
                        {
                            ID = 184,
                            CountryName = "Guyana",
                            Permitted = true
                        },
                        new
                        {
                            ID = 185,
                            CountryName = "Colombia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 186,
                            CountryName = "Chile",
                            Permitted = true
                        },
                        new
                        {
                            ID = 187,
                            CountryName = "Suriname",
                            Permitted = true
                        },
                        new
                        {
                            ID = 188,
                            CountryName = "Trinidad and Tobago",
                            Permitted = true
                        },
                        new
                        {
                            ID = 189,
                            CountryName = "Brazil",
                            Permitted = true
                        },
                        new
                        {
                            ID = 190,
                            CountryName = "Bolivia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 191,
                            CountryName = "Paraguay",
                            Permitted = true
                        },
                        new
                        {
                            ID = 192,
                            CountryName = "Peru",
                            Permitted = true
                        },
                        new
                        {
                            ID = 193,
                            CountryName = "Venezuela",
                            Permitted = true
                        },
                        new
                        {
                            ID = 194,
                            CountryName = "Argentina",
                            Permitted = true
                        },
                        new
                        {
                            ID = 195,
                            CountryName = "Uruguay",
                            Permitted = true
                        },
                        new
                        {
                            ID = 196,
                            CountryName = "Ecuador",
                            Permitted = true
                        },
                        new
                        {
                            ID = 197,
                            CountryName = "South Ossetia",
                            Permitted = true
                        },
                        new
                        {
                            ID = 198,
                            CountryName = "Somaliland",
                            Permitted = true
                        },
                        new
                        {
                            ID = 199,
                            CountryName = "Northern Cyprus",
                            Permitted = true
                        },
                        new
                        {
                            ID = 200,
                            CountryName = "Taiwan",
                            Permitted = true
                        },
                        new
                        {
                            ID = 201,
                            CountryName = "Transnistria",
                            Permitted = true
                        },
                        new
                        {
                            ID = 202,
                            CountryName = "Nagorno-Karabakh",
                            Permitted = true
                        },
                        new
                        {
                            ID = 203,
                            CountryName = "Sahrawi Arab Democratic Republic",
                            Permitted = true
                        },
                        new
                        {
                            ID = 204,
                            CountryName = "Abkhazia",
                            Permitted = true
                        });
                });

            modelBuilder.Entity("Application.Model.Information", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InformationAddressID")
                        .HasColumnType("int");

                    b.Property<int?>("InformationOccupationID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("InformationAddressID");

                    b.HasIndex("InformationOccupationID");

                    b.ToTable("Informations");
                });

            modelBuilder.Entity("Application.Model.Occupation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccupationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("Application.Model.Information", b =>
                {
                    b.HasOne("Application.Model.Address", "InformationAddress")
                        .WithMany()
                        .HasForeignKey("InformationAddressID");

                    b.HasOne("Application.Model.Occupation", "InformationOccupation")
                        .WithMany()
                        .HasForeignKey("InformationOccupationID");

                    b.Navigation("InformationAddress");

                    b.Navigation("InformationOccupation");
                });
#pragma warning restore 612, 618
        }
    }
}
